version: '3'

services:
  ingest:
    container_name: ingest
    build:
      context: ./ingest
      dockerfile: Dockerfile
    env_file:
      - ingest/config
    ports:
      - "8888:8888"
    volumes:
      - ./ingest/src:/opt/src
    networks:
      - local
 
  plot:
    container_name: plot
    build:
      context: ./plotly
      dockerfile: Dockerfile
    env_file:
      - ./plotly/config
    ports:
      - "8877:8888"
      - "8989:80"
      - "4443:443"
    volumes:
      - ./plotly/src:/opt/src
    networks:
      - local

  datalake:
    image: minio/minio
    container_name: datalake
    ports:
        - "9999:9000"
        - "9991:9001"
    volumes:
        - datalake:/data
    env_file:
        - datalake/config
    command: server --console-address ":9001" /data
    networks:
        - local
  # Relational Database/Data Warehouse
  database:
      image: postgres:13
      container_name: warehouse
      env_file:
          - warehouse/config
      volumes:
          - warehouse:/var/lib/postgresql/data
      healthcheck:
          test: [ "CMD", "pg_isready", "-U", "mydb"]
          interval: 5s
          retries: 5
      restart: always
      ports:
          - "5432:5432"
      networks:
          - local
  dbeaver:
    image: dbeaver/cloudbeaver
    container_name: dbeaver
    ports:
      - "8787:8978"
    networks:
      - local
    volumes:
      - dbeaver:/opt/cloudbeaver/workspace
  viz:
        image: metabase/metabase
        container_name: viz
        env_file:
            - viz/config
        volumes:
            - metabase-data:/metabase-data
        ports:
            - "3000:3000"
        networks:
            - local

networks:
  local:
volumes:
  datalake:
  warehouse:
  dbeaver:
  metabase-data: